server:
  servlet:
    context-path: /onlinevotingsystem

spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/}${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
    default-schema: ${DB_SCHEMA}

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false

hibernate:
  transaction:
    coordinator_class:

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLE:true}
    defaultModelsExpandDepth: -1

